### PR TITLE
minor spelling edits; add PKS link

### PR DESCRIPTION
**Pull request by deadlysyn**
hello drnic :-)

working through your excellent book to learn bosh as a new Pivotal employee...first, thanks for the resource!

trying to make minor fixes as i go to feel useful...also trying to be mindful of Queen's English (hello 'ageing' vs 'aging'! :-) ) so as not to bog you down with silly edits.  not sure how you feel about 'ise' vs 'ize', i did change that one since wikipedia seems to say even the Queen (or at least Oxford) prefers 'ize'.  Long Live The Queen!

https://en.wikipedia.org/wiki/American_and_British_English_spelling_differences#-ise,_-ize_(-isation,_-ization)

granted, this is likely yet another conspiracy by an american organization to pollute proper English!

of course, if you flat-out deny this i completely understand...with or without these edits, the content is amazing.  i'll still feel productive, having used vim and git all in one day!

### CODE REVIEW

**Comment by drnic** [comment]
-ize is an American conspiracy to deny their rightful place in the British empire. The Queen will fix this. She has Prince Harry on the job. Bwhahahaha

**Comment by drnic** [comment]
Let’s keep the -ise suffixes. It’s more fun that way. I think the other changes look good. Sorry to push back and not just merge.

**Comment by deadlysyn** [comment]
LOL.  no worries at all, i'll revert the 'ise' bits and re-push after standups.

one question before i continue -- is PR-per-page actually helpful, or you'd prefer one PR across the rest of the book as i work through it?  at first i thought multi-PR made sense, but now i realize it's starting to smell like spam (and not the yummy wasubi kind).

thanks for your guidance.

**Comment by drnic** [comment]
I'm fine with a hundred PRs. I know its easy to create tiny PRs when editing the pages via github.com so I'm happy for you to use that.

**Pull request merged**
